ALTER TABLE url ADD COLUMN groupKey VARCHAR(128) DEFAULT NULL;
ALTER TABLE url ADD COLUMN valid BOOLEAN DEFAULT NULL;
ALTER TABLE status MODIFY method VARCHAR(10) DEFAULT NULL;
CREATE INDEX url_groupKey ON url(groupKey);